# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=30)),
                ('street_name', models.CharField(max_length=30)),
                ('suburb', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_finance', models.BooleanField()),
                ('include_installation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Financier',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Client')),
                ('company_name', models.CharField(max_length=30)),
                ('company_reg', models.CharField(max_length=40)),
                ('web_address', models.URLField(null=True)),
            ],
            bases=('app.client',),
        ),
        migrations.CreateModel(
            name='GeyserSystemOrder',
            fields=[
                ('systemorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.SystemOrder')),
                ('property_type', models.CharField(max_length=10)),
                ('roof_inclination', models.CharField(max_length=10)),
                ('existing_geyser', models.BooleanField()),
                ('new_system', models.BooleanField()),
                ('water_collector', models.CharField(max_length=30)),
                ('current_geyser_size', models.PositiveSmallIntegerField(null=True)),
                ('users_number', models.PositiveSmallIntegerField(null=True)),
                ('required_geyser_size', models.PositiveSmallIntegerField(null=True)),
                ('same_as_existing', models.BooleanField()),
            ],
            bases=('app.systemorder',),
        ),
        migrations.CreateModel(
            name='PVTSystem',
            fields=[
                ('systemorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.SystemOrder')),
                ('intended_use', models.CharField(max_length=50)),
                ('site_visit', models.BooleanField()),
                ('property_type', models.CharField(max_length=10)),
                ('roof_inclination', models.CharField(max_length=10)),
                ('possible_appliances', models.ManyToManyField(to='app.Appliance')),
            ],
            bases=('app.systemorder',),
        ),
        migrations.CreateModel(
            name='SolarComponent',
            fields=[
                ('systemorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.SystemOrder')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('app.systemorder',),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='system',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.SystemOrder'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='physical_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.PhysicalAddress'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SupplierInstaller',
            fields=[
                ('financier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Financier')),
                ('systems', models.ManyToManyField(to='app.System')),
            ],
            bases=('app.financier',),
        ),
    ]
